// Generated by https://quicktype.io

export interface ProgramasResponse {
  page:          number;
  results:       Movie[];
  total_pages:   number;
  total_results: number;
}

export interface Movie {
  adult:             boolean;
  backdrop_path:     string;
  id:                number;
  name:              string;
  original_language: OriginalLanguage;
  original_name:     string;
  overview:          string;
  poster_path:       string;
  media_type:        MediaType;
  genre_ids:         number[];
  popularity:        number;
  first_air_date:    string;
  vote_average:      number;
  vote_count:        number;
  origin_country:    OriginCountry[];
}

export enum MediaType {
  Tv = "tv",
}

export enum OriginCountry {
  CN = "CN",
  Jp = "JP",
  Kr = "KR",
  Us = "US",
}

export enum OriginalLanguage {
  En = "en",
  Ja = "ja",
  Ko = "ko",
  Zh = "zh",
}
